[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
# Fixed command - Railway doesn't support ${VAR:-default} syntax
startCommand = "gunicorn --workers=3 --timeout=120 --bind 0.0.0.0:$PORT app:app"
healthcheckPath = "/api/health"
healthcheckTimeout = 600
healthcheckInterval = 30
healthcheckStartPeriod = 180
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
MAX_WORKERS = "3"
MAX_SESSIONS = "20"
SESSION_TTL = "300"
CLEANUP_INTERVAL = "60"
MAX_MEMORY_PERCENT = "80"
