[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
# Remove startCommand to let the Dockerfile CMD run properly
healthcheckPath = "/api/health"
healthcheckTimeout = 60
healthcheckInterval = 15
# Allow more startup time for model loading
healthcheckStartPeriod = 180
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
MAX_WORKERS = "3"
MAX_SESSIONS = "30"
SESSION_TTL = "600"
CLEANUP_INTERVAL = "120"
MAX_MEMORY_PERCENT = "85"
MODELS_DIR = "/app/models"
ALLOWED_ORIGINS = "*"
