[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 600
healthcheckInterval = 30
healthcheckStartPeriod = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
MAX_WORKERS = "3"
MAX_SESSIONS = "30"
SESSION_TTL = "600"
CLEANUP_INTERVAL = "120"
MAX_MEMORY_PERCENT = "85"
MODELS_DIR = "/app/models"
