[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "gunicorn --workers=${MAX_WORKERS:-2} --timeout=120 --bind 0.0.0.0:${PORT:-5000} app:app"
healthcheckPath = "/api/health"
healthcheckTimeout = 600
healthcheckInterval = 30  # Check every 30 seconds
healthcheckStartPeriod = 180  # Wait 2 minutes before first check
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
MAX_WORKERS = "3"
MAX_SESSIONS = "20"
SESSION_TTL = "300"
CLEANUP_INTERVAL = "60"
MAX_MEMORY_PERCENT = "80"
